# Generated by Django 4.0.1 on 2022-02-08 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 11, 4, 9, 817601, tzinfo=utc)),
        ),
    ]
