# Generated by Django 4.0.1 on 2022-02-07 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 19, 15, 53, 9552, tzinfo=utc)),
        ),
    ]
