# Generated by Django 4.0.1 on 2022-01-25 09:28

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published_post_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 9, 28, 35, 712738, tzinfo=utc)),
        ),
    ]
