# Generated by Django 4.0.1 on 2022-02-02 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 16, 50, 49, 127957, tzinfo=utc)),
        ),
    ]
