# Generated by Django 4.0.1 on 2022-02-06 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_rename_poster_post_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='posts_like', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось пользователям'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 10, 2, 30, 882448, tzinfo=utc)),
        ),
    ]
