from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('posts/create/',
         views.PostCreateView.as_view(),
         name='post_create'),
    path('posts/edit/header/<int:post_id>/',
         views.PostUpdateView.as_view(),
         name='post_header_edit'),
    path('posts/delete/<int:post_id>/',
         views.PostDeleteView.as_view(),
         name='post_delete'),
    path('posts/edit/<int:post_id>/<str:model_name>/create/',
         views.ContentCreateUpdateView.as_view(),
         name='content_create'),
    path('posts/edit/<int:post_id>/<str:model_name>/update/<int:content_object_id>/',
         views.ContentCreateUpdateView.as_view(),
         name='content_update'),
    path('posts/edit/<int:post_id>/delete/<int:content_id>/',
         views.ContentDeleteView.as_view(),
         name='content_delete'),
    path('posts/edit/<int:post_id>/',
         views.PostPreviewEditView.as_view(),
         name='post_edit'),
    path('posts/edit/<int:post_id>/publish/',
         views.publish_post_view,
         name='post_publish'),
    path('posts/',
         views.PostListView.as_view(),
         name='post_list'),
    path('posts/<slug:category_slug>/',
         views.PostListView.as_view(),
         name='post_list_by_category'),
    path('<str:username>/posts/',
         views.UserPostListView.as_view(),
         name='users_post_list'),
    path('<str:username>/posts/<slug:category_slug>/',
         views.UserPostListView.as_view(),
         name='users_post_list_by_category'),
    path('posts/detail/<int:post_id>/',
         views.PostDetailView.as_view(),
         name='post_detail'),
    path('like/',
         views.PostLikeView.as_view(),
         name='post_like')
]
